NodeRPC = "node"
DatabaseConnectionURL = "postgres://root:admin@?host=%2Fvar%2Ffolders%2F5l%2Frsbdhptd0tsgd07nqx0f4r7w0000gn%2FT%2Fdemo196079099&port=26257" 
Type = "gaia"
Debug = true

[Gaia]
ProcessorsEnabled = ["bank","ibc"]
