// Code generated by "stringer -type WritebackStatementTypes"; DO NOT EDIT.

package tracelistener

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Delete-0]
	_ = x[Write-1]
}

const _WritebackStatementTypes_name = "DeleteWrite"

var _WritebackStatementTypes_index = [...]uint8{0, 6, 11}

func (i WritebackStatementTypes) String() string {
	if i >= WritebackStatementTypes(len(_WritebackStatementTypes_index)-1) {
		return "WritebackStatementTypes(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WritebackStatementTypes_name[_WritebackStatementTypes_index[i]:_WritebackStatementTypes_index[i+1]]
}
