queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=2"

pull_request_rules:
  - name: automatic merge for main when CI passes and 2 reviews
    conditions:
      - "#approved-reviews-by>=2"
      - check-success=lint (v42)
      - check-success=code_cov (v42)
      - check-success=lint (v44)
      - check-success=code_cov (v44)
      - base=main
      - label=automerge
    actions:
      queue:
        name: default
        method: squash
        commit_message_template: |
           {{ title }} (#{{ number }})
           {{ body }}
  - name: delete head branch on merged pull requests
    conditions:
      - merged
    actions:
      delete_head_branch:
