name: Build docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - cmd/**
      - tracelistener/**
      - utils/**
      - go.mod
      - go.sum
      - helm/**

jobs:
  tracelistener:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile
          tags: gcr.io/tendermint-dev/emeris-tracelistener:${{ steps.get_version.outputs.version-without-v }},gcr.io/tendermint-dev/emeris-tracelistener:${{ github.sha }}
          build-args: |
            GIT_TOKEN=${{ secrets.TENDERBOT_GIT_TOKEN }}