name: Build docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - cmd/**
      - tracelistener/**
      - utils/**
      - go.mod
      - go.sum
      - helm/**

jobs:
  run-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Set allinbits org as GOPRIVATE
        run: go env -w GOPRIVATE=github.com/allinbits/*

      - name: Set git rewrite for private repos
        run: git config --global url."https://git:${{ secrets.TENDERBOT_GIT_TOKEN }}@github.com".insteadOf "https://github.com"

      - name: Run tests
        run: go test ./...

  build-tracelistener-image:
    runs-on: self-hosted
    needs: run-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile
          tags: gcr.io/tendermint-dev/emeris-tracelistener:${{ steps.get_version.outputs.version-without-v }},gcr.io/tendermint-dev/emeris-tracelistener:${{ github.sha }}
          build-args: |
            GIT_TOKEN=${{ secrets.TENDERBOT_GIT_TOKEN }}
