name: Lint
on:
  pull_request:
permissions:
  contents: read
env:
  GOPRIVATE: "github.com/emerishq,github.com/allinbits"

jobs:
  setup-matrix:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Setup matrix combinations
        id: setup-matrix-combinations
        run: |
          MATRIX_PARAMS_COMBINATIONS="$(make versions-json)"
          echo ::set-output name=matrix-combinations::{\"include\":$MATRIX_PARAMS_COMBINATIONS}
    outputs:
      matrix-combinations: ${{ steps.setup-matrix-combinations.outputs.matrix-combinations }}

  golangci:
    name: lint
    runs-on: self-hosted
    needs: setup-matrix
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix-combinations) }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Configure git for private modules
        env:
          GIT_TOKEN: ${{ secrets.TENDERBOT_GIT_TOKEN }}
        run: git config --global url."https://git:${GIT_TOKEN}@github.com".insteadOf "https://github.com"

      - name: Setup multisdk
        run: make setup-${{ matrix.versions }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: v1.45
          args: --timeout 10m --build-tags sdk_${{ matrix.versions }}
          github-token: ${{ secrets.TENDERBOT_GIT_TOKEN }}
