name: Release

on:
  pull_request:
    types: [closed]

  workflow_dispatch:

jobs:
  release:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
          tag_format: "v%major%.%minor%.%patch%"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
