name: Run tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "*"
    paths:
      - cmd/**
      - tracelistener/**
      - utils/**
      - go.mod
      - go.sum

jobs:
  gotest:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Set allinbits org as GOPRIVATE
        run: go env -w GOPRIVATE=github.com/allinbits/*

      - name: Set git rewrite for private repos
        run: git config --global url."https://git:${repo-token}@github.com".insteadOf "https://github.com"
        with:
          repo-token: ${{ secrets.TENDERBOT_GIT_TOKEN }}

      - name: Run tests
        run: go test ./...
