name: Tests / Code Coverage

on:
  workflow_dispatch:
  pull_request:
  push:

env:
  CODECOV_TOKEN: ff2cfeec-40e2-4740-a91c-16c63efd432c

jobs:
  code_cov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Setup token for pulling from allinbits private repos
        run: |
          go env -w GOPRIVATE=github.com/PrathyushaLakkireddy/*
          git config --global url."https://git:${{ secrets.TENDERBOT_GIT_TOKEN }}@github.com".insteadOf "https://github.com"

      - name: Build
        run: go build -v ./...

      - name: Run coverage
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
